version: '3.8'

services:
  nest_api_postgres:
    image: postgres:alpine
    container_name: nest_api_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - nest_api_postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: nestjs_starter

volumes:
  nest_api_postgres_data: