name: Build and Deploy ECR to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 686255981564.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build and push Docker image
        run: |
            docker build -t nest-api .
            docker tag nest-api:latest 686255981564.dkr.ecr.ap-southeast-1.amazonaws.com/nest-api:latest
            docker push 686255981564.dkr.ecr.ap-southeast-1.amazonaws.com/nest-api:latest

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: |
            TAG=${TAG}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=ap-southeast-1
          script: |
            echo "AWS CLI version: $(aws --version)"
            echo "Docker version: $(docker --version)"

            echo "Stop the current running container if exist..."
            sudo docker stop nest-api || true
            sudo docker stop pgadmin || true

            echo "Remove the previous container..."
            sudo docker rm nest-api || true
            sudo docker rm pgadmin || true

            echo "Logging in to ECR...."
            aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 686255981564.dkr.ecr.ap-southeast-1.amazonaws.com
            echo "Logged in successful..."

            echo "Pulling  image from ECR..."
            sudo docker pull 686255981564.dkr.ecr.ap-southeast-1.amazonaws.com/nest-api:latest
            echo "Docker pull completed..."

            echo "Running the container..."

            sudo docker run -d --name pgadmin \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER}} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD}} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB}} \
              -e PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL}} \
              -e PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD}} \
              -p 8080:80 dpage/pgadmin4:6.18 \
              -v /data/pgadmin:/root/.pgadmin

            sudo docker run -d \
              --name nest-api \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -p 80:3000 686255981564.dkr.ecr.ap-southeast-1.amazonaws.com/nest-api:latest